### ISSUE TITLE
Trigger element dissappears

### ISSUE THREAD

**Issue by pmerryfellow** [gilbitron/Dropit#15]
When I click the menu trigger a second time (once it's expanded, in order to close it) it gets hidden.

I can't see why this is happening, could you perhaps see where I've gone wrong?

The markup is:

    <ul id="l10n-menu">
        <li>
            <a href="#" class="current-locale en_GB">
                v
            </a>
            <ul>
                <li>
                    <a href="?locale=en_US" class="en">English (US)</a>
                </li>
                <li>
                    <a href="?locale=ur" class="ur" dir="rtl">Urdu</a>
                </li>
            </ul>
        </li>
    </ul>

And my init code is:

    $(document).ready(function () {
        $('#l10n-menu').dropit();
    });

**Comment by pmerryfellow** [comment]
Oh, and if I click anywhere else to drop focus, it works normally, only when I click the trigger element.

**Comment by mattgiltaji** [comment]
changing this

    $(this).parents(settings.triggerParentEl).removeClass('dropit-open').find(settings.submenuEl).hide();

to this

    $('.dropit-open').removeClass('dropit-open').find('.dropit-submenu').hide();

seems to fix it for me.

**Comment by artefactio** [comment]
I had the same issue too. It seems to happen when Dropit is nested inside another list. Thumbs up @mattgiltaji your fix worked for me.

**Comment by pmerryfellow** [comment]
Fantastic, that looks like it will sort it. I've tried it in a sandbox and it works, I will have to try it in the original project later, but I'm sure this will have fixed it. 

Cheers!
