### ISSUE TITLE
Is there a way to hide the submenu ONLY if the trigger is clicked or if a click occurs outside the submenu?

### ISSUE THREAD

**Issue by sciascia** [gilbitron/Dropit#8]
Hi There,

This menu is working great but two drop downs in our main nav contain a shopping cart and a search form.

The issue is that if a person clicks within the submenu, the menu disappears - i.e. if they click the search form or items in the cart, everything gets hidden.

Is there a way to hide the submenu ONLY if a trigger is clicked or if a click occurs outside the submenu?

I've tried targeting a class for the trigger element but like most jQuery plugins, there are no examples that show the correct syntax for adding the settings (I find javascript very confusing sorry).

I've tried:

```
  <script>
    $(document).ready(function() {
      $('.dropit').dropit(
          triggerEl: 'a.dropit-trigger-element', // The trigger element
      );
    });
  </script>
```

and...

```
  <script>
    $(document).ready(function() {
      $('.dropit').dropit(
        {
          triggerEl: 'a.dropit-trigger-element', // The trigger element
        }
      );
    });
  </script>
```

BTW, I'm using [this](https://github.com/gilbitron/Dropit/pull/5) pull request from 5months ago because [this more recent pull request](https://github.com/gilbitron/Dropit/pull/7) leaves a previous submenu open if a new one is triggered.

Sorry if this is easy - any pointers in the right direction would be much appreciated.

Cheers

Ben

**Comment by Jolva** [comment]
The above referenced fix is a 404. Does anyone else have a solution?

**Comment by studioraygun** [comment]
@popc0rn I realise it's been a couple of years but do you still have the documentation for that broken link? Thanks!

**Comment by popc0rn** [comment]
@studioraygun this should be my [forked repo](https://github.com/popc0rn/tinydrop) that I renamed later on if I'm not mistaken. Don't even look at the commits because there is a lot of garbage as I was trying something out. But you could take a look at **example.html** and see if it works as you want.
Hopefully that is what you're looking for and you can pull out **.js** and **.css** files and use it.
Cheers!
